add second step

diff --git a/.github/workflows/functions_workflow.yml b/.github/workflows/functions_workflow.yml
--- a/.github/workflows/functions_workflow.yml
+++ b/.github/workflows/functions_workflow.yml
@@ -5,7 +5,7 @@ jobs:
         runs-on: ubuntu-latest
         steps:
             - name: first step
-              run: sleep 50
+              run: exit 1
             - name: Runs on Cancelled
               if: ${{ cancelled() }}
               run: echo "This job was cancelled"
@@ -18,3 +18,10 @@ jobs:
             - name: Runs on failure
               if: ${{ failure() }}
               run: echo "This job runs only if the previous job failed"
+    second-job:
+        runs-on: ubuntu-latest
+        needs: functions-command
+        if: ${{failure()}}
+        steps:
+            - name: second step
+              run: echo "This job runs only if the first job failed"
